enum ActionTypes {
    AUTH_LOADING = "AUTH_LOADING",
    AUTH_AUTHENTICATION = "AUTH_AUTHENTICATION",
    AUTH_VALIDATE = "AUTH_VALIDATE",
    AUTH_SET_USER = "AUTH_SET_USER",
    AUTH_VALIDATE_USERNAME = "AUTH_VALIDATE_USERNAME",
    AUTH_VALIDATE_EMAIL = "AUTH_VALIDATE_EMAIL",
    AUTH_FAIL = "AUTH_FAIL",
    AUTH_LOGOUT = "AUTH_LOGOUT",

    PRODUCTS_LOADING = "PRODUCTS_LOADING",
    PRODUCTS_SET = "PRODUCTS_SET",

    CART_INITIALIZE = "CART_INITIALIZE",
    CART_LOADING = "CART_LOADING",
    CART_SET = "CART_SET",
    CART_ADD = "CART_ADD",
    CART_REMOVE = "CART_REMOVE",
    CART_UPDATE = "CART_UPDATE",
};
export default ActionTypes;