enum ActionTypes {
    AUTH_LOADING = "AUTH_LOADING",
    AUTH_AUTHENTICATION = "AUTH_AUTHENTICATION",
    AUTH_VALIDATE = "AUTH_VALIDATE",
    AUTH_SET_USER = "AUTH_SET_USER",
    AUTH_VALIDATE_USERNAME = "AUTH_VALIDATE_USERNAME",
    AUTH_VALIDATE_EMAIL = "AUTH_VALIDATE_EMAIL",
    AUTH_FAIL = "AUTH_FAIL",
};
export default ActionTypes;